config/routes.rb
Rails.application.routes.draw do
	root 'restaurants#index'
	resources :restaurants do
		resources :reviews
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews
	
	validates :name, presence: true
	validates :address, presence: true
	validates :city, presence: true
	validates :state, presence: true
	validates :zip, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	
	validates :restaurant, presence: true
	validates :rating, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
    	flash[:notice] = "Restaurant added successfully!"
      redirect_to @restaurant
    else
    	flash[:alert] = "Failed to save restaurant!"
    	@form_error = @restaurant.errors.full_messages
      render :new
    end
	end

	def show
		@restaurant = Restaurant.find(params[:id])
		@reviews = @restaurant.reviews
	end

	private

	def restaurant_params
		params.require(:restaurant).permit(
			:name,
			:address,
			:city,
			:state,
			:zip,
			:description
		)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@review = Review.new
		@restaurant = Restaurant.find(params[:restaurant_id])
	end

	def create
		@review = Review.new(review_params)
		@restaurant = Restaurant.find(params[:restaurant_id])
		@review.restaurant_id = @restaurant.id
    if @review.save
    	flash[:notice] = "Review added successfully!"
      redirect_to @restaurant
    else
    	flash[:alert] = "Failed to save review"
    	@form_error = @review.errors.full_messages
      render :new
    end
	end

	private

	def review_params
		params.require(:review).permit(
			:rating,
			:body
		)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantReviews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/index.html.erb
<div>Dan's Restaurant Review Site<div><br>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div>
	<%= link_to 'Add Restaurant', new_restaurant_path %>
</div> <br>

<ul>
	<% @restaurants.each do |restaurant| %>
		<li><%= link_to restaurant.name, restaurant_path(restaurant.id) %></li>
	<% end %>	
</ul>

app/views/restaurants/new.html.erb
<div>Add Restaurant</div> <br>

<%= form_for @restaurant do |f| %>
	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :address %>
		<%= f.text_field :address %>
	</div>

	<div class="field">
		<%= f.label :city %>
		<%= f.text_field :city %>
	</div>

	<div class="field">
		<%= f.label :state %>
		<%= f.text_field :state %>
	</div>

	<div class="field">
		<%= f.label :zip %>
		<%= f.text_field :zip %>
	</div>

	<div class="field">
		<%= f.label :description %>
		<%= f.text_field :description %>
	</div> <br>

	<div class="actions">
		<%= f.submit "Add Restaurant" %>
	</div>
<% end %>

<% if @form_error %>
	<% @form_error.each do |error| %>
		<p><%= error %><p>
	<% end %>
<% end %>

app/views/restaurants/show.html.erb
<div>
	<%= @restaurant.name %> <br>
	<%= @restaurant.address %>, 
	<%= @restaurant.city %>, 
	<%= @restaurant.state %> 
	<%= @restaurant.zip %> <br>
	<%= @restaurant.description %>
</div>
<br>

<div>
	<%= link_to "Review #{@restaurant.name}", new_restaurant_review_path(@restaurant) %>
</div> <br>

<% if flash[:notice] %>
	<div class="notice"><%= flash[:notice] %></div> <br>
<% end %>

<ul>	
	<% @reviews.each do |review| %>
		<%= review.rating %> stars out of 5 <br>
		<%= review.body %> <br>
		<%= review.created_at.strftime("%B %d %Y") %> <p>
	<% end %>
</ul>

app/views/reviews/new.html.erb
<div>Review <%= @restaurant.name %></div> <br>

<%= form_for [@restaurant, @review] do |f| %>
	<div class="field">
		<%= f.label :rating, "Rating (1-5)"%>
		<%= f.text_field :rating %>
	</div>

	<div class="field">
		<%= f.label :body, "Body" %>
		<%= f.text_field :body %>
	</div> <br>

	<div class="actions">
		<%= f.submit "Add Review" %>
	</div>
<% end %>

<% if @form_error %>
	<% @form_error.each do |error| %>
		<p><%= error %><p>
	<% end %>
<% end %>	